### ISSUE TITLE
Vue: refreshPage action may not trigger view update

### ISSUE THREAD

**Issue by BaerMitUmlaut** [embedpdf/embed-pdf-viewer#196]
There is an edge case where, after the opened document is switched, the currently shown page does not belong to the current document. My loading code to open a PDF at a given page looks like this (slightly trimmed):

```ts
const pdf = await loaderProvider.value!.loadDocument({
  pdfFile: {
    content: arrayBuffer,
    id: generateUniqueId(),
  },
  type: "buffer",
});

zoomProvider.value?.requestZoom(ZoomMode.FitPage);

let unsubscribe: Unsubscribe | undefined = undefined;
unsubscribe = viewportProvider.value?.onViewportChange(() => {
  scrollProvider.value?.scrollToPage({ pageNumber: page ?? 1, behavior: "instant" });
  unsubscribe?.();
});
```

Reproduction: I have two documents, A and B, between which I switch like so:
1. Open document A at page 4
2. Open document B at page 1
3. Scroll to page 5 (using `scrollProvider.value?.scrollToPage({ pageNumber: 5, behavior: "instant" })`)
4. Open document A at page 4

At this point, page 4 of document B is shown. Text is not selectable despite selection layer.

I attempted to force a redraw by dispatching the refreshPage action 3 seconds after the document was opened:
```ts
contextState.registry.value?.getStore().dispatchToCore(refreshPages([page]))
```
The log output indicated a render was happening (`WebWorkerEngine.Engine.renderPage.Begin`). I also set breakpoints on any call of `URL.createObjectURL` which again indicated to me that something was rendered (assuming I hit [render-page.tsx](https://github.com/embedpdf/embed-pdf-viewer/blob/4dcb6eaf0b500b59d2dcc97db5038bcd3a449256/website/src/content/docs/react/code-examples/render-page.tsx#L90)). The resulting URL did not match the URL in the DOM and the wrong page was still visible. My conclusion is that the correct page _is_ getting rendered (even without manually triggering the action), but the DOM isn't updated.

Manually adding a [Vue key](https://vuejs.org/api/built-in-special-attributes#key) to the `RenderLayer` to update it after opening the document fixed the issue but adds a slight delay when opening a document (I assume because the visible pages now get rendered twice).

**Comment by bobsingor** [comment]
@BaerMitUmlaut This should be fixed now: b1e881a

**Comment by BaerMitUmlaut** [comment]
This fixes the symptoms, but doesn't fix the underlying issue in my opinion. I've dug further and found out the following:

- My `dispatchToCore` call did not work because pages are apparently internally zero indexed - with the page number - 1, the call works
- [`onRefreshPages`](https://github.com/embedpdf/embed-pdf-viewer/blob/2d7c306e1ccb56703cf61686c474ef9be9de4337/packages/plugin-render/src/vue/components/render-layer.vue#L85) is not raised by default on document switch
- None of the other [watched properties](https://github.com/embedpdf/embed-pdf-viewer/blob/2d7c306e1ccb56703cf61686c474ef9be9de4337/packages/plugin-render/src/vue/components/render-layer.vue#L98) are changed on document switch

That's the core reason why the page is not correctly rerendered. So either the render plugin needs to raise `onRefreshPages` on document load or a secondary event needs be added or the document id need to be added to the watched properties.
